version: "3.7"
services:  
  python: #docker run -it -v ${PWD}:/work -w /work -p 5003:5000 epigardenia/python:1.0.0 /bin/sh
    container_name: python
    image: epigardenia/python:1.0.0
    build: 
      context: ./Python
      target: debug
    #working_dir: /work      #comment out for build.target:prod
    #entrypoint: /bin/sh     #comment out for build.target:prod
    #stdin_open: true        #comment out for build.target:prod
    #tty: true               #comment out for build.target:prod
    volumes:
    - ./Python/src/:/work
    ports:
    - 5003:5000
    - 5678:5678

