version: "3.7"
services:  
  python: #docker run -it -v ${PWD}:/work -w /work -p 5003:5000 epigardenia/python:1.0.0 /bin/sh
    container_name: python
    image: epigardenia/python:1.0.0
    build: ./Python
    target: prod
    #working_dir: /work      #comment out for build.target:prod
    #entrypoint: /bin/sh     #comment out for build.target:prod
    #stdin_open: true        #comment out for build.target:prod
    #tty: true               #comment out for build.target:prod
    volumes:
    - ./Python/src/:/work
    ports:
    - 5003:5000

  java:
    container_name: java
    image: epigardenia/java:1.0.0
    build: ./Java

  swift:
    container_name: swift
    image: epigardenia/swift:1.0.0
    build: ./Swift
    working_dir: /work
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes:
    - ./Swift/src/:/work
    ports:
    - 5002:5000
